# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  outputDirectory = "./fastlane/builds/"
  alias_keyStore = "ConcentrixOne"
  password_keyStore = "c0nc3ntrix0n3"
  password_key = "c0nc3ntrix0n3"

  desc "clean and Build **************************************************"
  lane :cleanAndbuild do
    gradle(task: "clean")
    gradle(task: " assembleRelease", print_command: false,
          properties: {
            "android.injected.signing.store.file" => '/Users/venkat/Desktop/CNX One Docs/ConcentrixOne.keystore',
            "android.injected.signing.store.password" => password_keyStore,
            "android.injected.signing.key.alias" => alias_keyStore,
            "android.injected.signing.key.password" => password_key,
          }
    )


  end

  desc "Increment version code **************************************************"
  lane :increment_version do
    increment_version_code(gradle_file_path: "./app/build.gradle")
  end

  desc "Setup APK file location **************************************************"
    lane :binary_path do
    copy_artifacts(artifacts: ['*/build/outputs/apk/**/*.apk'], target_path: outputDirectory)
    echo(message:"APK copied successfully================================================================= #{outputDirectory}")
  end

  desc "Sharing Build"
  lane :uploadToDiawi do |values|
    diawi(token: values[:token], file: values[:file])
  end

  desc "Build **************************************************"
    lane :build do
      increment_version
      cleanAndbuild
      binary_path
      uploadToDiawi token: "yyUqLNEoWKnkeJeGmSC45GH2Gkc7U9sLV3Vv7ATiLI", file: "./fastlane/builds/app-release.apk"
end 

end
